services:
  - type: web
    name: scuds
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: scuds-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true